"""Harvest Spark's own function categories into priv/function_groups.exs.

    python dev/harvest_function_groups.py [--write]

`Latu.Functions.Registry` carries name, wire name and arity, and no category — so a flat page
of 671 name/arity pairs has nothing to group by. PySpark's own API reference does: every
function it exposes is listed under one heading in

    python/docs/source/reference/pyspark.sql/functions.rst

at the tag Latu targets. Same provenance as the registry itself (the Connect client), keyed the
same way (PySpark's name, which is Latu's), so the join is exact rather than fuzzy.

Not taken from Scala's `@ExpressionDescription(group: ...)` annotations: those are spread over
hundreds of files, keyed by wire name rather than by PySpark's, and would need a checkout.

Needs network. Run it on a machine that has one; the output is checked in, as
`priv/function_docs.exs` is.
"""

import argparse
import pathlib
import re
import sys
import urllib.request

TAG = "v4.2.0"
URL = (
    f"https://raw.githubusercontent.com/apache/spark/{TAG}"
    "/python/docs/source/reference/pyspark.sql/functions.rst"
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "lib/latu/functions/registry.ex"
FUNCTIONS = ROOT / "lib/latu/functions.ex"
OUTPUT = ROOT / "priv/function_groups.exs"

# Names Latu exports that the reference does not list, with the reason. Anything else missing is
# reported and left ungrouped rather than filed under a default -- a wrong group is worse than
# none, and a silent default is how a taxonomy rots.
EXTRA = {
    "call_function": "Normal Functions",
    "when_": "Conditional Functions",
    "otherwise": "Conditional Functions",
    # Absent from Spark's own reference, which is an upstream gap rather than a category:
    # `bitmap_or_agg` and `bitmap_construct_agg` are both listed under Aggregate Functions.
    "bitmap_and_agg": "Aggregate Functions",
}


def groups_from(rst):
    """{group title: [name]} — a heading, its underline, then an autosummary block."""
    groups, current, lines = {}, None, rst.split("\n")

    for i, line in enumerate(lines):
        if re.fullmatch(r"-{3,}", line) and lines[i - 1].strip():
            current = lines[i - 1].strip()
            groups.setdefault(current, [])
        elif current and re.fullmatch(r"    [a-z_][a-z_0-9]*", line):
            groups[current].append(line.strip())

    return {title: names for title, names in groups.items() if names}


def latu_names(registry, functions):
    """Every name `Latu.Functions` exports, generated or hand-written.

    A registry row is `{:name, "wire", ...}`, so the quoted wire name is what tells one apart
    from a nested tuple like `{:fixed, 1}` in the same literal. The hand-written half is the
    keyword list `handwritten/0` returns; both halves need a group, since ExDoc groups the
    module page and not the registry.
    """
    generated = {m.group(1) for m in re.finditer(r'\{:([a-z_0-9]+), "', registry)}

    block = re.search(r"def handwritten do(.*?)\n  end", functions, re.S)
    written = {m.group(1) for m in re.finditer(r"^\s+([a-z_0-9]+_?): \d+,?$", block.group(1), re.M)}

    return sorted(generated | written)


def render(pairs):
    body = "\n".join(f'  "{name}" => "{group}",' for name, group in pairs)

    return (
        f"# Generated by dev/harvest_function_groups.py from Spark {TAG}. Do not hand-edit.\n"
        "#\n"
        "# Keyed by Latu's own function name, which is PySpark's. Read by Latu.Functions at\n"
        "# compile time and emitted as `@doc group:`, which is how ExDoc groups a module page.\n"
        "%{\n" + body + "\n}\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write priv/function_groups.exs")
    args = parser.parse_args()

    groups = groups_from(urllib.request.urlopen(URL).read().decode("utf-8"))
    of = {name: title for title, names in groups.items() for name in names}
    of.update(EXTRA)

    names = latu_names(REGISTRY.read_text(), FUNCTIONS.read_text())
    missing = sorted(name for name in names if name not in of)

    print(f"{len(groups)} groups over {len(of)} names in the reference")
    print(f"{len(names)} names read out of the registry and handwritten list, {len(missing)} of")
    print("them absent from the reference")

    if missing:
        print("\nabsent — add to EXTRA with a reason, or leave ungrouped deliberately:")
        for name in missing:
            print(f"  {name}")

    print(
        "\nNames built from a module attribute are invisible to this script; "
        "`test/latu/functions_test.exs` is what proves every export has a group."
    )

    if args.write:
        OUTPUT.write_text(render(sorted(of.items())))
        print(f"\nwrote {OUTPUT.relative_to(ROOT)}")
    else:
        print("\n--write to update priv/function_groups.exs")

    return 0


if __name__ == "__main__":
    sys.exit(main())
