#!/usr/bin/env python3
"""Harvest Spark's own function documentation into a build artifact.

Spark documents itself: `DESCRIBE FUNCTION EXTENDED <name>` returns usage and examples for
every builtin. Running it once against the version Latu targets beats scraping, and it cannot
drift from the server. The output is checked in, so nobody needs a server to compile.

Needs a running Connect server.

A clean run prints two lines: the count, and the few names PySpark wraps that Spark's own
catalogue does not list. Anything prefixed `!!` is a real failure and exits non-zero.

    docker compose up -d spark-connect
    . dev/.venv/bin/activate
    python dev/harvest_docs.py                     # writes priv/function_docs.exs
    python dev/harvest_docs.py --remote sc://host:15002

Rerun after a Spark version bump, and commit the diff.
"""

import argparse
import json
import logging
import os
import pathlib
import subprocess
import sys

HEADER = """# Generated by dev/harvest_docs.py against Spark %s. Do not hand-edit.
#
# Keyed by Spark's *wire* function name, which is not always PySpark's name for it —
# `count_distinct` is `count` here. Read by Latu.Functions.Docs at compile time.
"""


def wire_names(here):
    """Every wire name Latu's registry uses, from the same source the registry comes from."""
    out = subprocess.run(
        [sys.executable, str(here / "extract_functions.py"), "--json"],
        capture_output=True,
        text=True,
        check=True,
    )
    rows = json.loads(out.stdout)

    # Irregular rows are hand-written rather than generated, but they are still Spark functions
    # and still want Spark's documentation — the higher-order ones are wrappers just the same.
    # A row with no wire name at all builds no UnresolvedFunction, so there is nothing to ask
    # about.
    return sorted({r["wire"] for r in rows if r.get("wire")})


# Spark's DESCRIBE output is a flat sequence of labelled sections. `Note:` is prose and must
# not end up inside the examples' code fence — 28 functions carry one, and "non-deterministic"
# is exactly the kind of thing a reader needs.
KEEP = {"Usage:": "usage", "Examples:": "examples", "Note:": "note"}
DROP = ("Function:", "Class:", "Extended Usage:", "Since:", "Arguments:", "Deprecated:")


def catalogue(spark):
    """Every function Spark's catalogue knows, lowercased and unqualified.

    Asked up front so that a name Spark simply does not have is skipped quietly instead of
    raising. Four of PySpark's wrappers name functions the catalogue does not list, and an
    exception traceback for each is alarming for something entirely expected.

    Returns an empty set if the query is unusable, which falls back to describing everything.
    """
    try:
        rows = spark.sql("SHOW FUNCTIONS").collect()
    except Exception:  # noqa: BLE001 — degrade to the old behaviour rather than abort
        return set()

    return {str(row[0]).strip().lower().rsplit(".", 1)[-1] for row in rows if row[0]}


def describe(spark, name):
    """Usage, examples and notes for one function.

    Returns `(entry, error)`: at most one is set. A bare `except` would make a real failure — a
    dead server, a permissions error — look identical to a function Spark has no docs for, so
    the reason is reported rather than swallowed. Reaching this at all means the catalogue
    listed the function, so an error here is worth shouting about.
    """
    try:
        rows = spark.sql("DESCRIBE FUNCTION EXTENDED `%s`" % name.replace("`", "")).collect()
    except Exception as exc:  # noqa: BLE001 — reported, not swallowed
        return None, "%s: %s" % (type(exc).__name__, str(exc).splitlines()[0][:120])

    sections = {key: [] for key in KEEP.values()}
    current = None
    for line in "\n".join(r[0] for r in rows).splitlines():
        stripped = line.strip()
        label = next((k for k in KEEP if stripped.startswith(k)), None)
        if label:
            current = sections[KEEP[label]]
            stripped = stripped[len(label) :].strip()
        elif stripped.startswith(DROP):
            current = None
            continue
        if current is not None and stripped:
            current.append(stripped)

    entry = {key: "\n".join(value) for key, value in sections.items()}
    if not entry["usage"] and not entry["examples"]:
        return None, "no Usage: or Examples: section"
    return entry, None


def elixir_string(value):
    """A Python string as an Elixir string literal.

    `json.dumps` escapes quotes and backslashes exactly as Elixir wants. Interpolation is the
    one thing it does not know about: an unescaped `#{` in a docstring is an Elixir syntax
    error, and Spark's SQL examples do contain it.
    """
    return json.dumps(value, ensure_ascii=False).replace("#{", "\\#{")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--remote", default=os.environ.get("SPARK_REMOTE", "sc://localhost:15002"))
    ap.add_argument("--out", type=pathlib.Path)
    args = ap.parse_args()

    here = pathlib.Path(__file__).resolve().parent
    out = args.out or here.parent / "priv" / "function_docs.exs"

    # Spark's client logs an analysis warning for a name it cannot resolve. Nothing here is
    # unexpected enough to warrant it, and it alarms in a script that ends "378 documented".
    logging.getLogger("pyspark").setLevel(logging.ERROR)

    from pyspark.sql import SparkSession

    spark = SparkSession.builder.remote(args.remote).getOrCreate()
    version = spark.version

    names = wire_names(here)
    known = catalogue(spark)

    # Trust the catalogue only if it looks like one. If it disagrees with more than a tenth of
    # the registry it is not what we think it is, and skipping on it would silently drop docs —
    # so fall back to describing everything, which cannot lose anything.
    absent = [n for n in names if n.lower() not in known]
    if not known or len(absent) > len(names) // 10:
        if known:
            print("SHOW FUNCTIONS disagrees with %d names; ignoring it" % len(absent))
        known, absent = set(), []

    skip = {n.lower() for n in absent}

    harvested, failed = {}, []
    for name in names:
        if name.lower() in skip:
            continue

        entry, error = describe(spark, name)
        if entry is None:
            failed.append((name, error))
        else:
            harvested[name] = entry

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as fh:
        fh.write(HEADER % version)
        fh.write("%{\n")
        for name in sorted(harvested):
            entry = harvested[name]
            fh.write("  %s => %%{\n" % elixir_string(name))
            fh.write('    "usage" => %s,\n' % elixir_string(entry["usage"]))
            fh.write('    "examples" => %s,\n' % elixir_string(entry["examples"]))
            fh.write('    "note" => %s\n' % elixir_string(entry["note"]))
            fh.write("  },\n")
        fh.write("}\n")

    print("%d of %d functions documented -> %s" % (len(harvested), len(names), out))

    if absent:
        print(
            "%d not in Spark's function catalogue, so not documented: %s"
            % (len(absent), ", ".join(absent))
        )

    # Only this is a problem: the catalogue listed it and it still would not describe.
    for name, error in failed:
        print("!! %s did not describe — %s" % (name, error))
    if failed:
        sys.exit("%d catalogued function(s) failed to describe" % len(failed))


if __name__ == "__main__":
    main()
