defmodule Latu.Wire do
  @moduledoc false
  # Golden plans, generated by `python dev/pyspark_oracle.py --generate`. See dev/README.md.
  # Loaded by test/test_helper.exs, so it stays out of the compiled application.

  import ExUnit.Assertions

  alias Latu.DataFrame
  alias Latu.Plan
  alias Latu.Protocol.Spark.Connect, as: Proto

  @dir "test/wire"

  @doc "Assert a plan is the one PySpark builds. Returns its argument, so it chains."
  def assert_wire(%DataFrame{} = df, name) do
    assert_wire(df.plan, name)
    df
  end

  def assert_wire(%Proto.Relation{} = relation, name) do
    expected = Proto.Plan.decode(File.read!(Path.join(@dir, "#{name}.bin")))
    assert relation |> Plan.normalize_ids() |> Plan.new() == expected
    relation
  end

  @doc "Like `assert_wire/2`, for a command — a write, SQL and catalog operations."
  def assert_wire_command(%Proto.Command{} = command, name) do
    expected = Proto.Plan.decode(File.read!(Path.join(@dir, "#{name}.bin")))
    assert command |> Plan.normalize_ids() |> Plan.new() == expected
    command
  end

  @doc """
  Like `assert_wire/2`, for a message that is not a plan — an `AnalyzePlan` request arm.

  Decodes with the message's own module, so the fixture and the value have to be the same
  message. The request envelope is not part of it: session id, user context and client type
  are the same for every arm.
  """
  def assert_wire_message(%module{} = message, name) do
    expected = module.decode(File.read!(Path.join(@dir, "#{name}.bin")))
    assert Plan.normalize_ids(message) == expected
    message
  end
end
